server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dongbao-mall?character-Encoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: zdf19941118.
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl